### ISSUE TITLE
New scaleway-cli release broke the action run

### ISSUE THREAD

**Issue by clementgoclock** [scaleway/action-scw#33]
Since new release v2.30.0 minutes ago.
```
1s
Run scaleway/action-scw@v0
  with:
    save-config: true
    export-config: true
    access-key: ***
    secret-key: ***
    default-project-id: ***
    default-organization-id: ***
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.[1](https://github.com/O-clock-Dev/terraform-infra/actions/runs/8691001241/job/23832188076#step:5:1)9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x64
    Python[2](https://github.com/O-clock-Dev/terraform-infra/actions/runs/8691001241/job/23832188076#step:5:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/O-clock-Dev/terraform-infra/actions/runs/8691001241/job/23832188076#step:5:3).9.19/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x6[4](https://github.com/O-clock-Dev/terraform-infra/actions/runs/8691001241/job/23832188076#step:5:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib
Didn't found CLI in cache, downloading v2.30.0
file:///home/runner/work/_actions/scaleway/action-scw/v0/dist/index.js:3389
            const err = new HTTPError(response.message.statusCode);
                        ^

HTTPError: Unexpected HTTP response: 404
    at file:///home/runner/work/_actions/scaleway/action-scw/v0/dist/index.js:3389:2[5](https://github.com/O-clock-Dev/terraform-infra/actions/runs/8691001241/job/23832188076#step:5:5)
    at Generator.next (<anonymous>)
    at fulfilled (file:///home/runner/work/_actions/scaleway/action-scw/v0/dist/index.js:3299:5[8](https://github.com/O-clock-Dev/terraform-infra/actions/runs/8691001241/job/23832188076#step:5:8))
    at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/O-clock-Dev/terraform-infra/actions/runs/8691001241/job/23832188076#step:5:9)5:5) ***
  httpStatusCode: 404
***

Node.js v20.8.1
```

Workaround: specify previous version at least, example GHA workflow:

```
    - name: Configure Scaleway CLI
      uses: scaleway/action-scw@v0
      with:
        save-config: true
        export-config: true
        version: v2.29.0
        access-key: ${{ secrets.SCW_BBB_ACCESS_KEY }}
        secret-key: ${{ secrets.SCW_BBB_SECRET_KEY }}
        default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
```
