### ISSUE TITLE
scw function list - failing API request with x509 error: certificate signed by unknown authority

### ISSUE THREAD

**Issue by domeales-paloit** [scaleway/action-scw#58]
Hi there,

I am enjoying this Github Action, thank you.

I am currently having an issue when I attempt to use the command `scw function function list`. When I run this I am getting:
```scaleway-sdk-go: error executing request: Get "https://api.scaleway.com/functions/v1beta1/regions/fr-par/functions?namespace_id=&order_by=created_at_asc&page=1": tls: failed to verify certificate: x509: certificate signed by unknown authority```

Is there something else I need to add before I can use this command?

Thanks for your help!!

---
Versions tried
* scw-cli versions: 2.24.0, 2.32.1
* action-scw: 0.0.2

deploy-function.yml
```yaml
name: Deploy function
run-name: 🚀 Deploy ${ github.ref }
on:
  workflow_dispatch:
jobs:
  deploy-preprod:
    name: Deploy to preprod
    env:
      ENVIRONMENT: preprod
    runs-on: ubuntu-latest
    steps:
      - name: Deploy function to Scaleway
        uses: scaleway/action-scw@v0.0.2
        with:
          version: 2.24.0
          save-config: true
          export-config: true
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      - name: Get function ID
        run: |
          set -ex
          scw function function list
```

Also tried using the `args` parameter of the action, and I get the same result.
