### ISSUE TITLE
Scaleway env variables leaks in Github Action log

### ISSUE THREAD

**Issue by rfrerebe** [scaleway/action-scw#74]
Hello,

Using command below to update a container, it will output the `environment_variables` property containing private information  defined in Scaleway interface.
This private info should not be **leaked** in github logs.

```yaml
- name: Update container version
      uses: scaleway/action-scw@v0
      with:
        access-key: ${{ secrets.SCW_ACCESS_KEY }}
        secret-key: ${{ secrets.SCW_SECRET_KEY }}
        default-project-id: ${{ secrets.SCW_PROJECT_ID }}
        default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}
        args: container container update ${{ secrets.CONTAINER_ID }} registry-image=rg.fr-par.scw.cloud/namespace/docker-image:${{ github.ref_name }}
```

Is there any option to mitigate this issue ?
